### ISSUE TITLE
in DisplayTftSpiBase the yMax and xMax calculations are commented out - causing second Show() to not display changes to the displaybuffer

### ISSUE THREAD

**Issue by MarkAlanJones** [WildernessLabs/Meadow.Foundation#120]
//will probably skip for now
            /*  xMin = (uint)Math.Min(xMin, x);
              xMax = (uint)Math.Max(xMax, x);
              yMin = (uint)Math.Min(yMin, y);
              yMax = (uint)Math.Max(yMax, y);  */

this is in SetPixel

**Comment by adrianstevens** [comment]
Thanks Mark - this change was intentional for performance reasons but it introduced this bug.

We pushed a fix to address the bug but I'm going to leave this issue open as reminder to retest. We're expecting to have some performance improvements in the near future that will allow us to re-enable this optimization.

**Comment by adrianstevens** [comment]
This was fixed a while back now - closing issue
